// Payment
export const PAYMENT_PER_HOUR = 30
export const HOURS_PER_DAY = 8
export const DAYS_PER_WEEK = 6
export const WEEK_PER_MONTH = 4
export const HOURS_PER_MONTH = HOURS_PER_DAY * DAYS_PER_WEEK * WEEK_PER_MONTH
// IVA
export const PERCENT_BASE_IVA = 0.09
export const PERCENT_BONUS_IVA = 0.03
export const PAYMENT_FOR_BONUS_IVA = 10000
// BONUS
export const PAYMENT_PER_DELIVERY = 5
export const PERCENT_BONUS_VOUCHERS = 0.04
export const PAYMENT_BONUS_PER_HOUR = {
  Chofer: 10,
  Auxiliar: 0,
  Cargador: 5,
}
export const CREATE_EMPLOYEE_TABLE_QUERY = `
    CREATE TABLE IF NOT EXISTS EMPLOYEES (
        ID SERIAL PRIMARY KEY,
        NUMBER INT NOT NULL,
        ROLE VARCHAR NOT NULL,
        NAME VARCHAR NOT NULL,
        DELIVERIES INT NOT NULL DEFAULT 0,
        WORKEDDATE DATE NOT NULL DEFAULT CURRENT_DATE,
        CREATEDAT DATE NOT NULL DEFAULT CURRENT_DATE
    );
`
export const SELECT_EMPLOYEE_TABLE_QUERY = `SELECT * FROM EMPLOYEES;`
export const SELECT_EMPLOYEE_BY_ID_QUERY = `SELECT * FROM EMPLOYEES WHERE ID = $1;`
export const DELETE_EMPLOYEE_TABLE_QUERY = `DELETE FROM EMPLOYEES WHERE ID = $1 RETURNING *;`
export const INSERT_EMPLOYEE_TABLE_QUERY = `INSERT INTO EMPLOYEES (NUMBER, ROLE, NAME)
VALUES($1, $2, $3) RETURNING *;`
export const UPDATE_EMPLOYEE_DATE_TABLE_QUERY = `UPDATE EMPLOYEES SET WORKEDDATE = $2 WHERE ID = $1;`
export const UPDATE_EMPLOYEE_IFORMATION_TABLE_QUERY = `UPDATE EMPLOYEES SET NUMBER = $2, ROLE = $3, NAME = $4 WHERE ID = $1;`
export const UPDATE_EMPLOYEE_DELIVERIES_TABLE_QUERY = `UPDATE EMPLOYEES SET DELIVERIES = $2 WHERE ID = $1;`
